To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://unsloth.ai/docs/get-started/install).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **Unsloth Studio** - a new open source, no-code web UI to train and run LLMs. [Blog](https://unsloth.ai/docs/new/studio) • [Notebook](https://colab.research.google.com/github/unslothai/unsloth/blob/main/studio/Unsloth_Studio_Colab.ipynb)

<table><tr>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FxV1PO5DbF3ksB51nE2Tw%252Fmore%2520cropped%2520ui%2520for%2520homepage.png%3Falt%3Dmedia%26token%3Df75942c9-3d8d-4b59-8ba2-1a4a38de1b86&width=376&dpr=3&quality=100&sign=a663c397&sv=2" width="200" height="120" alt="Unsloth Studio Training UI"></a><br><sub><b>Train models</b> — no code needed</sub></td>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FRCnTAZ6Uh88DIlU3g0Ij%252Fmainpage%2520unsloth.png%3Falt%3Dmedia%26token%3D837c96b6-bd09-4e81-bc76-fa50421e9bfb&width=376&dpr=3&quality=100&sign=c1a39da1&sv=2" width="200" height="120" alt="Unsloth Studio Chat UI"></a><br><sub><b>Run GGUF models</b> on Mac, Windows & Linux</sub></td>
</tr></table>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os, importlib.util
!pip install --upgrade -qqq uv
if importlib.util.find_spec("torch") is None or "COLAB_" in "".join(os.environ.keys()):
    try: import numpy, PIL; _numpy = f"numpy=={numpy.__version__}"; _pil = f"pillow=={PIL.__version__}"
    except: _numpy = "numpy"; _pil = "pillow"
    !uv pip install -qqq \
        "torch==2.8.0" "triton>=3.3.0" {_numpy} {_pil} torchvision bitsandbytes xformers==0.0.32.post2 \
        "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
        "unsloth[base] @ git+https://github.com/unslothai/unsloth"
elif importlib.util.find_spec("unsloth") is None:
    !uv pip install -qqq unsloth
!uv pip install --upgrade --no-deps tokenizers trl==0.22.2 unsloth unsloth_zoo
!uv pip install transformers==5.2.0
# causal_conv1d is supported only on torch==2.8.0. If you have newer torch versions, please wait 10 minutes!
!uv pip install --no-build-isolation flash-linear-attention causal_conv1d==1.6.0

#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

We're also introducing how you can do `GSPO` inside of Unsloth as well!

The goal of this notebook is to make a vision language model solve maths problems via reinforcement learning given an image input like below:

<img src="https://raw.githubusercontent.com/lupantech/MathVista/main/assets/our_new_3_datasets.png" alt="Alt text" height="256">

In [2]:
from unsloth import FastVisionModel
import torch
max_seq_length = 16384 # Must be this long for VLMs
lora_rank = 16 # Larger rank = smarter, but slower

model, tokenizer = FastVisionModel.from_pretrained(
    model_name = "unsloth/Qwen3.5-4B",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = False, # Enable vllm fast inference
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.4.4: Fast Qwen3_5 patching. Transformers: 5.2.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.4.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using float16 precision for qwen3_5 won't work! Using float32.
Unsloth: QLoRA and full finetuning all not selected. Switching to 16bit LoRA.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/723 [00:00<?, ?it/s]

processor_config.json: 0.00B [00:00, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

preprocessor_config.json:   0%|          | 0.00/336 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/20.0M [00:00<?, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

In Unsloth, we share vLLM's weights directly, reducing VRAM usage by > 50%. vLLM also does not yet support LoRA on the vision layers, so we can only add them on the language layers. Vision GRPO still works though!

In [3]:
model = FastVisionModel.get_peft_model(
    model,
    finetune_vision_layers     = False, # False if not finetuning vision layers
    finetune_language_layers   = True,  # False if not finetuning language layers
    finetune_attention_modules = True,  # False if not finetuning attention layers
    finetune_mlp_modules       = True,  # False if not finetuning MLP layers

    r = 16,           # The larger, the higher the accuracy, but might overfit
    lora_alpha = 16,  # Recommended alpha == r at least
    lora_dropout = 0,
    bias = "none",
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    # target_modules = "all-linear", # Optional now! Can specify a list if needed
)

Unsloth: Making `model.base_model.model.model.language_model` require gradients

### Data Prep
<a name="Data"></a>

`AI4Math/MathVista` is a dataset that involves using images to solve logic and math problems.

For this notebook, we will only use math problems with numeric answers for simplicity.

In [ ]:
# from datasets import load_dataset
# from trl import GRPOConfig, GRPOTrainer

# dataset = load_dataset("AI4Math/MathVista", split = "testmini")

README.md: 0.00B [00:00, ?B/s]

data/testmini-00000-of-00001-725687bf7a1(…):   0%|          | 0.00/142M [00:00<?, ?B/s]

data/test-00000-of-00002-6b81bd7f7e2065e(…):   0%|          | 0.00/358M [00:00<?, ?B/s]

data/test-00001-of-00002-6a611c71596db30(…):   0%|          | 0.00/386M [00:00<?, ?B/s]

Generating testmini split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5141 [00:00<?, ? examples/s]

In [4]:
import pandas as pd
from datasets import Dataset

# Load your own CSV file
my_df = pd.read_csv('/content/train_qa.csv')
display(my_df.head())

# Convert the pandas DataFrame to a Dataset object
csv_dataset = Dataset.from_pandas(my_df)

# Replace the original dataset with the one loaded from CSV
dataset = csv_dataset

                                 question        answer
0  What is the type of "One Reem Island"?      projects
1           What is the type of "Rivage"?      projects
2         What is the type of "Ville 11"?      projects
3         What is the type of "Ville 11"?  subcommunity
4         What is the type of "The Gate"?      projects

We filter the dataset to keep only float or numeric answers:

In [ ]:
# def is_numeric_answer(example):
#     try:
#         float(example["answer"])
#         return True
#     except:
#         return False

# dataset = dataset.filter(is_numeric_answer)

Filter:   0%|          | 0/1000 [00:00<?, ? examples/s]

We also resize the images to be 512 by 512 pixels to make the images manageable in context length. We also convert them to RGB so they are compatible for training!

In [ ]:
# Resize to (512, 512)
# def resize_images(example):
#     image = example["decoded_image"]
#     image = image.resize((512, 512))
#     example["decoded_image"] = image
#     return example
# dataset = dataset.map(resize_images)

# # Then convert to RGB
# def convert_to_rgb(example):
#     image = example["decoded_image"]
#     if image.mode != "RGB":
#         image = image.convert("RGB")
#     example["decoded_image"] = image
#     return example
# dataset = dataset.map(convert_to_rgb)

Map:   0%|          | 0/566 [00:00<?, ? examples/s]

Map:   0%|          | 0/566 [00:00<?, ? examples/s]

We then create the conversational template that is needed to collate the dataset for RL:

In [19]:
# Define the delimiter variables for clarity and easy modification
REASONING_START = "<REASONING>"
REASONING_END = "</REASONING>"
SOLUTION_START = "<SOLUTION>"
SOLUTION_END = "</SOLUTION>"

def make_conversation(example):
    # Define placeholder constants if they are not defined globally
    # The user's text prompt
    text_content = (
        f"{example['question']}."
        f" Then your final answer between {SOLUTION_START} and {SOLUTION_END}"
    )

    # Construct the prompt in the desired multi-modal format
    prompt = [
        {
            "role": "user",
            "content": [
                # {"type": "image"},  # Placeholder for the image
                {"type": "text", "text": text_content},  # The text part of the prompt
            ],
        },
    ]
    # The actual image data is kept separate for the processor
    return {"prompt": prompt,
            # "image": example["decoded_image"],
            "answer": example["answer"]}

train_dataset = dataset.map(make_conversation)

# # We're reformatting dataset like this because decoded_images are the actual images
# # The "image": example["decoded_image"] does not properly format the dataset correctly

# # 1. Remove the original 'image' column
# train_dataset = train_dataset.remove_columns("image")

# # 2. Rename 'decoded_image' to 'image'
# train_dataset = train_dataset.rename_column("decoded_image", "image")

Map:   0%|          | 0/1427 [00:00<?, ? examples/s]

Now let's apply the chat template across the entire dataset:

## Reward functions

We now define some basic formatting rewards functions to see if reasoning starts and ends, and also another to see if the answers were written correctly.

We also try to fix the `addCriterion` issue as described in our [blog post](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl#qwen-2.5-vl-vision-rl-issues-and-quirks)

In [20]:
# Reward functions
import re

def formatting_reward_func(completions,**kwargs):
    import re
    thinking_pattern = f'{REASONING_START}(.*?){REASONING_END}'
    answer_pattern = f'{SOLUTION_START}(.*?){SOLUTION_END}'

    scores = []
    for completion in completions:
        if isinstance(completion, list):
            completion = completion[0]["content"] if completion else ""
        score = 0
        thinking_matches = re.findall(thinking_pattern, completion, re.DOTALL)
        answer_matches = re.findall(answer_pattern, completion, re.DOTALL)
        if len(thinking_matches) == 1:
            score += 1.0
        if len(answer_matches) == 1:
            score += 1.0

        # Fix up addCriterion issues
        # See https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl#qwen-2.5-vl-vision-rl-issues-and-quirks
        # Penalize on excessive addCriterion and newlines
        if len(completion) != 0:
            removal = completion.replace("addCriterion", "").replace("\n", "")
            if (len(completion)-len(removal))/len(completion) >= 0.5:
                score -= 2.0

        scores.append(score)
    return scores


def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    answer_pattern = f'{SOLUTION_START}(.*?){SOLUTION_END}'

    completions = [(c[0]["content"] if c else "") if isinstance(c, list) else c for c in completions]
    responses = [re.findall(answer_pattern, completion, re.DOTALL) for completion in completions]
    q = prompts[0]
    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:{completions[0]}")
    return [
        2.0 if len(r)==1 and a == r[0].replace('\n','') else 0.0
        for r, a in zip(responses, answer)
    ]

Here is the first example prompt in the dataset

In [21]:
train_dataset[0]["prompt"]

[{'content': [{'text': 'What is the type of "One Reem Island"?. Then your final answer between <SOLUTION> and </SOLUTION>',
    'type': 'text'}],
  'role': 'user'}]

In [22]:
train_dataset[100]["prompt"]

[{'content': [{'text': 'What is the type of "Ville 12"?. Then your final answer between <SOLUTION> and </SOLUTION>',
    'type': 'text'}],
  'role': 'user'}]

<a name="Inference"></a>
### Inference
Now let's try the model on the hundredth sample of the train dataset without training.

In [26]:
prompt = train_dataset[20]["prompt"]

inputs = tokenizer(
    images = None, # Explicitly pass None for images as there are none
    text = prompt, # Pass the conversational prompt as text
    add_special_tokens = False,
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 1024,
                   use_cache = True, temperature = 0.01, min_p = 0.1)

The term "Westminster Tower" most commonly refers to the **Elizabeth Tower** (formerly known as the Big Ben) located in the Palace of Westminster in London. In this context, it is a **clock tower** that serves as the most prominent landmark of the UK Parliament.

While there are other structures with similar names (such as the Westminster Abbey tower or various residential towers in cities like Westminster, California), the primary historical and cultural reference is to the clock tower housing the Great Bell.

<SOLUTION>Clock tower</SOLUTION><|im_end|>

<a name="Train"></a>
### Train the model

Now set up the `GRPO` Trainer and all configurations! Note we actually enable `GSPO` as well!

In [28]:
from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    learning_rate = 5e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.99,
    weight_decay = 0.1,
    warmup_ratio = 0.1,
    lr_scheduler_type = "cosine",
    optim = "adamw_8bit",
    logging_steps = 1,
    log_completions = False,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 2, # Decrease if out of memory
    max_prompt_length = 1024,
    max_completion_length = 1024,
    # num_train_epochs = 0.5, # Set to 1 for a full training run
    max_steps = 60,
    save_steps = 60,
    max_grad_norm = 0.1,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    # Below enables GSPO:
    importance_sampling_level = "sequence",
    mask_truncated_completions = False,
    loss_type = "dr_grpo",
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 2

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

During inference, you might encounter `addCriterion` or some weird gibberish outputs. Please read our [blog post](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl#qwen-2.5-vl-vision-rl-issues-and-quirks) on why this occurs. It seems to be an inherent thing inside of the model, and we can ignore this.

In [29]:
trainer = GRPOTrainer(
    model = model,
    args = training_args,
    # Pass the processor to handle multimodal inputs
    processing_class = tokenizer,
    reward_funcs = [
        formatting_reward_func,
        correctness_reward_func,
    ],
    train_dataset = train_dataset,
)

trainer.train()

Unsloth: Switching to float32 training since model cannot work with float16

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,427 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 1 x 1) = 2
 "-____-"     Trainable parameters = 32,464,896 of 4,571,730,432 (0.71% trained)

-------------------- Question:
[{'content': [{'text': 'What is the type of "Right Capital 1"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
projects
Response:The term "Right Capital 1" (often seen in fonts, logos, or currency symbols) refers to a specific glyph that acts as a replacement or modifier for the standard uppercase letter "A".

Here is the breakdown:
1.  **Context**: In many sans-serif fonts (like Arial) and in financial/corporate contexts, the letter "A" is expanded to enclose a dot, creating a symbol $\mathbf{\$A}$ or $\mathbf{\$ \! \# A}$ (depending on the specific design variations, but visually often appearing as $A$ with a dot).
2.  **Function**: This character functions as a **variable font glyph** or a **ligature variant**. It is not a standard Latin alphabet letter.
3.  **Technical Classification**: When typed in certain contexts (like the Chinese Pinyin for "Capital A" sometimes being mapped to this symbol $\ddot{A}$ or `$A`), it represents the uppercase letter 'A' with a specific modification (usually an acute accent or a dot). However, strictly speaking in typography and character sets, it is a distinct character often used to denote **Capital A** in specific style sets (like money fonts or decorative typefaces) or it is a **modifier letter**.

In the most common standard context (Western typography), this specific shape (an 'A' with a dot) is technically classified as a **Modifier Letter** (specifically the Modifier Letter U+02AA URRH OR DIAERESIS, sometimes rendered as `$A` in specific encodings) OR simply as a **Capital A** variant within a specific **Google Font** or **Currency Font** set.

However, if referring to the specific "Right Capital 1" identifier found in specific font metadata (like the *Capital* group in a font's glyph array) or in the context of the "Right Capital" symbol from specific datasets (like OCR character recognition, where 'A' with a specific dot is distinct):
It is primarily a representation of **Capital A** (specifically $\ddot{A}$ or $\dot{A}$ depending on the font design, often used for "Money" or "Acronyms").

If this is a reference to a specific question from a dataset regarding OCR or character recognition (where "Right Capital" refers to capitalized letters on the right side of the input stream), the type is simply **Capital A** (or **Letter A**).

But looking at the exact phrasing "Right Capital 1", this often appears in the context of defining the character **'A'** itself with a specific style (like the one used for currency).

Let's reconsider the "Right Capital" terminology. In many programming or data contexts, characters are categorized as "Upper", "Lower", "Digit", etc. "Right Capital 1" is likely a specific label for the **Uppercase Letter A** in a specific classification schema (perhaps distinguishing it from "Left Capital" or "Standard Capital" based on alignment or specific font properties).

Regardless of the specific identifier "Right Capital 1", the character it represents is the **Letter A** (Uppercase).

<ANSWER>
The type is **Capital A** (or **Uppercase Letter A**).
</ANSWER>

Based on the analysis of typographic standards and font glyph identifiers:
The "Right Capital 1" typically refers to a specific glyph used to represent the **Capital Letter A** (A) in certain specialized fonts, currency symbols, or OCR datasets. It is a variant of the Uppercase 'A'.

< SOLUTION> Capital A </SOLUTION>

-------------------- Question:
[{'content': [{'text': 'What is the type of "Al Ghadeer 2"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
projects
Response:Based on the naming convention of "Al Ghadeer" (referencing the Battle of Ghadeer Khumm in Islamic history) and the ordinal number "2," the most logical classification within the context of sports competitions—specifically football (soccer)—is a continuation or sequel to a previous event. The most prominent "Al Ghadeer" football team is a club based in Iraq. In sports trivia or context, a team labeled "Al Ghadeer 2" typically represents a **reserve team** or a **second team** created to feed talent to the main squad or compete in lower divisions.

However, if this refers to a specific, perhaps fictional or less common entity simply named "Al Ghadeer 2" in a database, the type would best be characterized as a **football club** (specifically a reserve or academy team).

Without specific context pointing to a movie, game, or obscure historical event other than football, the standard interpretation for "Team X 2" is a **reserve team** or **secondary football team**.

<SOLUTION>reserve team</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Ali & Sons Real Estate LLC"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
company_profile
Response:Ali & Sons Real Estate LLC is a business entity registered under the limited liability company (LLC) structure. In the United States, an LLC is a type of business organization that combines the limited liability features of a corporation with the tax and operational benefits of a partnership or sole proprietorship. The name explicitly includes "LLC," which stands for Limited Liability Company. This legal structure protects the personal assets of the owners (members) from business debts and liabilities, provided laws are followed, while offering flexibility in management and tax treatment (which may be passed through to the owners' personal tax returns or, less commonly, taxed as a corporation).

<SOLUTION>
Limited Liability Company (LLC)
</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Burj Views"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
subcommunity
Response:The term **"Burj Views"** generally refers to the panoramic vistas, skyline, or visual attractions offered by skyscrapers in Dubai, particularly those associated with the **Burj Khalifa** (the world's tallest building).

Specifically:
1.  **Contextual Meaning**: In tourism and hospitality, "Burj Views" is not a specific standalone product type like "software" or "food." Instead, it describes the **experience** of viewing the city skyline from high altitudes.
2.  **Associated Entities**: It is most commonly linked to the **observation decks** located within the Burj Khalifa, specifically **At the Top** (levels 124-125) and **At the Top SKY** (levels 128 and 148). These are commercial observation towers offering sightseeing tours, restaurants, and photography opportunities.
3.  **Categorization**: Therefore, the type is best classified as a **tourist attraction** or a **sightseeing experience** (specifically involving observation decks and skyline viewing).

<SOLUTION>Tourist attraction (Observation Deck) / Sightseeing Experience</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Sama Yas"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
subcommunity
Response:The term **"Sama Yas"** (often written in English as "Samey's" or referred to as the same brand) refers to **Jollibee**, the fast-food chain based in the Philippines.

You are likely hearing this term due to a specific phonetic misinterpretation or a very localized slang, but the most accurate explanation is a confusion of names or a mishearing of **"Chick-fil-A"** in certain regions? No, that doesn't fit well. Let's reconsider.

Actually, "Sama Yas" is most likely a mishearing or misspelling of **"Sharma's"** (a very common Philippine fast food chain) or more specifically, it is a dialectal/filipino slang pronunciation of **"Samey"**?

Wait, let's look at the most prominent brand associated with this sound in the Philippines. The most famous chain often abbreviated or colloquially referred to in specific contexts is **Sama's Restaurant** (now **SAMA**). It is a well-known fast-food chain in the Philippines known for its burgers and fries. The name is an acronym originally for **S**pecial **A**nimals and **M**eat, but often stylized as "Sama's".

However, there is a stronger candidate: **Jollibee** is owned by Sama Yas? No.

Let's re-evaluate the name "Sama Yas". It is actually a very common mistake for **"Sharma's"** in some contexts, OR it refers to **Sama's Restaurant Group**.

But looking at viral trends or common linguistic errors: "Sama Yas" sounds Hindi/Urdu for "Aloha" or similar? No.

Let's go back to the Philippines context which is the most likely source. There is a chain called **Sama's Restaurant** (founded in 2000). However, the specific phrase "Sama Yas" is almost certainly a mishearing of **"Jollibee's"**? No.

Actually, the most direct answer is that **"Sama Yas"** is not a standard English brand name. It is likely a mishearing of **"Chick-fil-A"** (unlikely), **"Shake Shack"** (unlikely), or specifically **"Sama's"**.

Wait, could it be a typo for **"Sam's"**?
Or is it **"Sumasama"**?

Let's try a different angle. Is it a specific song? No.
Is it a specific drink?

Let's assume the user is referring to the Philippine chain **Sama's Restaurant**. In the Philippines, "Sama" is a word meaning "peace" or "friend".
However, if we search for "Sama Yas" specifically, the most common result is a confusion with **"Jollibee"**? No.

Actually, there is a high probability the user is asking about **"Sharma's"** but got the name completely wrong, OR they are asking about **"Sama's"** and the "Yas" part is a suffix or sound.

**Correction/Refinement:**
There is a fast-food chain called **Sama's**. The name comes from the acronym **S**pecial **A**nimals and **M**eat.
However, the phrase "Sama Yas" is likely a mishearing of **"Sameas"**?
Or, is it possible it refers to the **Sama Yas** variety of something in India?

Let's consider the possibility of it being **"Chai"** related?

**Actual Realization:**
"Sama Yas" is likely a **mishearing of "Chokas"?** No.
"Sama Yas" -> **"Sharma's"**?
"Sama Yas" -> **"Sama's"**?

Let's look at the brand **Sama's Restaurant**. They are in the Philippines.
Is there a **"Sama Yas"**?
Ah, perhaps it is **"Sam's Club"** with "Yas" added?
Or **"Sama Yash"**?

Let's try a completely different path. Is it a language term?
"Sama" = Same/Equal. "Yas" = No?

**Final Check:**
Could it be **"Same Day"**?
Could it be **"Chaska"**?

Wait, I recall a viral sound or a specific chain in the **Philippines** called **Sama's**.
But if the name is strictly "Sama Yas", it might be a **typo for "Sharma's"** (a very popular burger chain in the Philippines).
OR, it could be a mishearing of **"Jollibee"** (Jolli -> Sama? No).

Let's reconsider the **Hindi** connection. "Yas" means nothing.
Maybe it's **"Sama Yash"**?

**Let's assume the user means "Sama's Restaurant
-------------------- Question:
[{'content': [{'text': 'What is the type of "Central District"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
community
Response:The term "Central District" typically refers to a specific **administrative division**, **city district**, or **locality** within a larger city or municipality. While the name itself is generic and could appear in many different cities around the world, when used in the context of geography or urban planning, it denotes a formally defined area for census, governance, or postal purposes.

If you are referring to specific instances (such as the Central District in London, or the Central District in Sydney), they are examples of **subdivisions of a city** or **local government areas**.

<SOLUTION>Administrative division / City district</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Hydra Phase 1"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
projects
Response:"Hydra Phase 1" typically refers to a specific stage within the planned development or execution of a project named "Hydra." Most notably, this appears in the context of the **HYDRA (Humanitarian and Yield-Derived Advanced)** initiative or similar conceptual frameworks where "Phase 1" denotes the initial implementation stage, often involving infrastructure setup, feasibility studies, or early deployment of core systems before scaling to subsequent phases.

However, without a specific context (such as a video game, a specific open-source project, a fictional work, or a real-world engineering plan), the term "Phase 1" generally denotes the **first stage** or **initial phase** of a multi-stage project lifecycle. It represents the foundational or preparatory step before advancement to later iterations.

In many contexts involving the word "Hydra" (which often implies complexity, regeneration, or multiple heads), "Phase 1" would logically be the **pilot**, **prototype**, or **foundation** stage designed to establish the necessary systems before addressing the more complex "regenerative" or multi-threat aspects represented by further phases.

If referring to a specific fictional context (like a game), it is simply a **stage** or **level** in a quest or difficulty progression. If referring to a real-world strategic plan, it is the **initial operational phase**.

Given the most common structural usage in project management and hypothetical strategic plans:

<SOLUTION>Initial Phase</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Al Habtoor Property Development L.L.C"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
company_profile
Response:Al Habtoor Property Development L.L.C. is a **company limited by shares** (a Limited Liability Company).

In the legal framework of the United Arab Emirates (where the company is registered), "L.L.C." stands for "Limited Liability Company." This type of entity is popular in Dubai and other UAE emirates because it offers limited liability to its owners, meaning their personal assets are generally protected from the company's debts and liabilities. It allows for private ownership and management and is commonly used for real estate development, property management, and holding companies involved in large-scale projects.

The company is famously associated with the Al Habtoor Group, a family-based conglomerate that manages several major business interests in Dubai, including the Al Habtoor Hospital and various luxury hotels and resorts (such as the Palm Jumeirah hotels formerly operated under related entities or partnerships).

<SOLUTION>Limited Liability Company</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Cornich Al Khalidiya"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
subcommunity
Response:The type of **"Cornich Al Khalidiya"** is a **sandwich**.

Specifically, "Al Khalidiya" (derived from the Arabic word *khalidi*, meaning veteran or traditional) refers to a style of sandwich that is stuffed between two pieces of pita bread. Despite its name suggesting a traditional or military-style snack, "Cornich Al Khalidiya" is famous for being a variation of a standard sandwich where the filling is often topped with a distinctive yellow sauce (typically mayonnaise mixed with mustard, paprika, and sometimes egg or cheese), and it is served with **freshly grated hard-boiled hard-boiled egg** (sometimes referred to as *mumtiaz*) on top. It is a popular street food in the Middle East, particularly in Egypt, though the preparation can vary by region. The "cornich" part indicates it is a small or specific type of sandwich, distinct from the larger "shawarma" or "takawta."

<SOLUTION>Sandwich</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Deyaar Development (P.J.S.C)"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
company_profile
Response:The type of **Deyaar Development (P.J.S.C.)** (Private Joint Stock Company) is a **Private Joint Stock Company**.

This entity operates as a non-quoted company owned and managed by individuals or shareholders (typically a consortium of real estate developers and investors). The designation "(P.J.S.C.)" explicitly identifies its legal structure under Saudi Arabian law, distinguishing it from either a public joint stock company (which is listed on a stock exchange and has shares in the public domain) or a limited liability company (LLC). Deyaar primarily engages in the development of real estate projects and investment portfolios in KSA.

<SOLUTION>Private Joint Stock Company</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "The Address Dubai Mall"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
subcommunity
Response:The **Address Dubai Mall** is a well-known luxury residential development located within the Dubai Mall complex in the Downtown Dubai area of the United Arab Emirates. It is not a standalone shopping center or a hotel, but rather a collection of high-end apartments, villas, and penthouses designed as a luxury residential community.

<SOLUTION>Residential
</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Al Falah City"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
community
Response:Al Falah City (also known as Al Falah Town) is not a standard or historically recognized major city in the Middle East or elsewhere under that exact name in general geographical databases. However, there are a few possibilities depending on the context:

1.  **Misspelling/Confusion with "Al Fallah"**: There is a well-known port city in Bahrain called **Al Fallah** (Alfalaa). It is an ancient city located near the southern port of Ar-Rawda, famous for its archaeological significance, the ancient Nabataean and Roman ruins (including the Temple of Atargatis), and its proximity to the Persian Gulf Oil Board. It is often confused with variations in transliteration.
2.  **Local/Sub-district Name**: It could refer to a specific residential town or development in a specific country (e.g., Saudi Arabia or another Gulf state) with the name "Al Falah City," which is a common naming convention in the region meaning "The Success."
3.  **Fictional/Historical**: It might refer to a fictional city in literature or a less documented historical town.

Given the phrasing and the likelihood of transliteration variance, the most probable intended target is **Al Fallah** (Alfalaa) in **Bahrain**, which is a **city** (specifically an old/ancient city and port town). If "Al Falah City" refers to a modern housing development in another country, it would simply be a **residential town** or **city**.

However, without a definitive source confirming a specific "Al Falah City" distinct from these, the safest classification based on common named entities with similar transliterations is that it refers to **Al Fallah, Bahrain**, which is a **city**.

<|SOLUTION>
City
</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Electra Street"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
community
Response:"Electra Street" is a fictional street featured in the 1958 science fiction television series **"The Twilight Zone"**, specifically in the episode titled "The Man without a Face" (though it appears in the opening sequence and is also associated with the overall concept of the show's mysterious setting). It is often listed as a **fictional street** used in the context of the television series.

However, there is another possibility: In some contexts, people might confuse it with real locations, but a quick verification shows there is no famous real-world place by that exact name that dominates search results like the fictional one from the *Twilight Zone*. Wait, actually, looking closer at trivia: The street address is usually discussed in relation to the fictionalized or unlisted addresses in the show.

Let's double-check. Is there a real "Electra Street"?
There is an **Electra Street** in **Carmiel, New York** (and possibly another in **Gainesville, Georgia** or similar small towns).
However, the question asks for "the type." If the user is referring to the famous pop culture reference, it's a **fictional street** from *The Twilight Zone*. If they are asking geographically, it could be a real street in a specific town.

Given the phrasing often found in trivia or general knowledge questions about "Electra Street" without specifying a city, the most distinct association is with **The Twilight Zone**, where the street is presented as a **fictional** location representing the unknown or unlisted.

BUT, let's look at the capitalization in the prompt: "Electra Street".
If this is a trick question about the show: In *The Twilight Zone*, the address block states "No 1226 Electra St., Apt 445" is where the episode begins/show opens, implying it's a **fictional address**.

Let's consider if the user means a specific real street. There is a street called Electra Street in Carmiel, NY. But "the type of Electra Street" sounds like it's asking for its *category* (e.g., fictional vs real) based on its fame.

Actually, the most common context for this specific naming convention in a "type" question without city context is the **fictional street** from *The Twilight Zone*. The street is part of the show's universe.

Wait, I need to be careful. Is there a definitive answer?
"The Twilight Zone" episode "The Man without a Face" runs 45 seconds with no audio, showing a woman's face peeling off. The opening credits show a street.
Actually, the famous line "Electra Street" is often associated with the **fictional** nature of the address.

Let's reconsider. Maybe it refers to the **fictional street** in *The Twilight Zone*.
Type: **Fictional street**.

Alternative interpretation: Is it a trick about the "Twilight Zone" address which is famously unlisted or unknown? The show implies the address is unknown.

Let's go with the most distinguishing characteristic. Since it doesn't have a single famous real-world counterpart that defines it globally (unlike, say, Bond Street), its primary "type" in cultural trivia is **fictional**.

**Final check:**
- Real world: Smaller streets exist, e.g., Carmiel, NY.
- Pop culture: Iconic fictional street from *The Twilight Zone*.

If the question implies the specific famous instance (which is the only way a query is typically asked without a city), the answer is **fictional**.

<SOLUTION>Fictional street</SOLUTION>
-------------------- Question:
[{'content': [{'text': 'What is the type of "Al Manaseer"?. Then your final answer between <SOLUTION> and </SOLUTION>', 'type': 'text'}], 'role': 'user'}]
Answer:
community

TrainOutput(global_step=60, training_loss=3.958365938320588e-06, metrics={'train_runtime': 2441.106, 'train_samples_per_second': 0.049, 'train_steps_per_second': 0.025, 'total_flos': 0.0, 'train_loss': 3.958365938320588e-06})

<a name="Inference"></a>
### Inference

Let's run the model! You can modify the instruction and input.

In [ ]:
# image = train_dataset[165]["image"]
prompt = train_dataset[165]["prompt"]

inputs = tokenizer(
    images = None, # Explicitly pass None for images as there are none
    text = prompt, # Pass the conversational prompt as text
    add_special_tokens = False,
    return_tensors = "pt",
).to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 1024,
                   use_cache = True, temperature = 0.01, min_p = 0.1)

The type of "The Row Saadiyat" is a **luxury hotel** (specifically, a 5-star hotel).

Located on Saadiyat Island in Abu Dhabi, United Arab Emirates, The Row Saadiyat is a boutique hotel designed by the renowned architect Jean Nouvel. It is part of the larger "The Row" development, which also includes a luxury residential complex and a private beach club. The hotel is known for its distinctive architectural design, featuring a unique "floating" structure over the water and a

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, use Hugging Face’s `push_to_hub` for online saving, or `save_pretrained` for local storage.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
model.save_pretrained("qwen_lora")  # Local saving
tokenizer.save_pretrained("qwen_lora")
# model.push_to_hub("your_name/qwen_lora", token = "YOUR_HF_TOKEN") # Online saving
# processor.push_to_hub("your_name/qwen_lora", token = "YOUR_HF_TOKEN") # Online saving

['grpo_lora/processor_config.json']

Verify LoRA is actually trained!

In [ ]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("qwen_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("qwen_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("qwen_lora")
    tokenizer.save_pretrained("qwen_lora")
if False:
    model.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/qwen_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

Special Credits to [GAD-Cell](https://github.com/GAD-cell) for helping Unsloth create this notebook and bringing VLM GRPO into Unsloth!
Now, use the `qwen_finetune.Q8_0.gguf` file or `qwen_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme)